import RoleGuard from "@/components/auth/RoleGuard";
import TenantSidebar from "@/components/shared/TenantSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RoleGuard allowedRole="tenant">
      <div className="min-h-screen my-2">
        <div className="flex min-h-screen w-screen">
          <div className="w-[20%]">
            <TenantSidebar />
          </div>
          <div className="w-[80%] bg-slate-100 rounded-xl ml-2">{children}</div>
        </div>
      </div>
    </RoleGuard>
  );
}
