import RoleGuard from "@/components/auth/RoleGuard";
import AdminSidebar from "@/components/shared/AdminSidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next Auth Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RoleGuard allowedRole="admin">
      <div className="min-h-screen my-2">
        <div className="flex justify-between">
          <div className="w-[20%]">
            <AdminSidebar />
          </div>
          <div className="w-[80%] bg-slate-100 rounded-xl ml-2">{children}</div>
        </div>
      </div>
    </RoleGuard>
  );
}
