// app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/providers/Providers';
import Navbar from '@/components/shared/Navbar';

export const metadata: Metadata = {
  title: 'Next Auth',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en" data-theme="light">
        <body>
          <Navbar />
          <div className="min-h-screen w-full mx-auto">{children}</div>
        </body>
      </html>
    </Providers>
  );
}
